### ISSUE TITLE
Unmarshal error on start

### ISSUE THREAD

**Issue by pdxjohnny** [drone-plugins/drone-ssh#7]
```log
Drone SSH Plugin built from dcc0d86
panic: Unable to unarmshal vargs. json: cannot unmarshal string into Go value of type int

goroutine 1 [running]:
github.com/drone/drone-go/plugin.MustParse()
	/drone/src/github.com/drone/drone-go/plugin/plugin.go:132 +0x59
main.main()
	/drone/src/github.com/drone-plugins/drone-ssh/main.go:28 +0x35a
[info] build failed (exit code 2)
```

This is my deploy using ssh plugin

```yml
deploy:
  ssh:
    host: server.example
    user: "$$SSH_USER"
    port: "$$SSH_PORT"
    commands:
      - cd ~/Documents/repo/
      - git pull
      - bash scripts/build.sh
      - docker-compose build
      - docker-compose stop
      - docker-compose rm -f
      - docker-compose up -d
```

What is the significance of `vagrs`?

**Comment by bradrydzewski** [comment]
Closing since plugin is upgraded to 0.5 and no longer uses Jason to provide configuration parameters to the plugin
